### ISSUE TITLE
Vinli dummy subcommands inconsistent on dummy ID parameter

### ISSUE THREAD

**Issue by gordysc** [vinli/vinli-cli#4]
A dummy device has an ID and a device ID.  We appear to be using the device ID for the route subcommand, but the actual dummy ID for the status subcommand.
<img width="965" alt="screen shot 2016-02-18 at 10 55 01 am" src="https://cloud.githubusercontent.com/assets/4010111/13151263/082e1694-d62f-11e5-9c93-269f8bedc4ee.png">

**Comment by gangstead** [comment]
It's definitely expecting a dummy id, not device id.  We check for an exact match by id and then do a closest-name search if there isn't an exact match [here](https://github.com/vinli/vinli-cli/blob/master/lib/fuzzy_find.js#L27).  In this case there isn't a dummy id that matches the device id passed in, so it does a fuzzy search of the dummy names (all "Virtual Vinli" in this case) and find the one that is closest to the device id.  Since the names are all the same they are all equally similar to the device id, so the first one is chosen.  If you were to start a route using another device id it will still start that first dummy in the list.

I'm going to add a check where if you pass in something that looks like a UUID and there isn't an exact match then it will throw an error.  I'll close this issue after that check is in place

**Comment by gangstead** [comment]
Try again and you should get an error message if you enter in a device id instead of a dummy id:
![image](https://cloud.githubusercontent.com/assets/527760/13158335/17e2ee0c-d652-11e5-8d47-3e9754e1a080.png)
